In [1]:
import numpy

ModuleNotFoundError: No module named 'numpy'

In [2]:
import numpy

In [4]:
import numpy as aafi

In [5]:
a=aafi.array([1,2,3])

In [6]:
print(a)

[1 2 3]


In [7]:
c=aafi.array([(1,2,3),(4,5,6)])

In [8]:
print(c)

[[1 2 3]
 [4 5 6]]


In [9]:
trans=aafi.transpose(c)

In [10]:
print(trans)

[[1 4]
 [2 5]
 [3 6]]


In [11]:
trans.ravel()

array([1, 4, 2, 5, 3, 6])

In [12]:
a.reshape(3,1)

array([[1],
       [2],
       [3]])

In [15]:
ze=aafi.zeros((3,1))

In [16]:
print(ze)

[[0.]
 [0.]
 [0.]]


In [17]:
c.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [20]:
ze=aafi.ones((1,3))

In [21]:
print(ze)

[[1. 1. 1.]]


In [22]:
aafi.random.random((4,4))

array([[0.49371162, 0.72664982, 0.66027484, 0.65362165],
       [0.82526087, 0.74056499, 0.77401471, 0.05039006],
       [0.47152495, 0.15917852, 0.86091923, 0.60915044],
       [0.26777452, 0.05126404, 0.4026087 , 0.03715337]])